def general():
            print(" ")
            print(" ")
            print(" ")
            print("--------------------")
            print("       Slexz")
            print("    Version 1.2.0 ")
            print("--------------------")
            print(" ")
            print(" ")
            print(" ")
